<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GOITT5R" failures="6" tests="53" name="sila_test_cases.Test_003_Register_add_registration_data" time="176.975" errors="0" timestamp="2020-12-09T12:35:29 IST" skipped="0">
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_001_registration_add_email_with_empty_user_handle" time="9.680"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_002_registration_add_empty_email_field" time="3.798"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_003_registration_add_email_with_invalid_private_key" time="3.584"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_004_registration_add_email_with_not_registered_handle" time="3.528"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_005_registration_add_invalid_email" time="3.752"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_006_registration_add_email_with_more_than_max_email_length" time="3.835">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_006_registration_add_email_with_more_than_max_email_length(Test_003_Register_add_registration_data.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_006_registration_add_email_with_more_than_max_email_length -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_007_registration_add_email_successfully_with_254_characters_email" time="3.643"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_008_registration_add_email_with_all_valid_data" time="3.706"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_009_registration_add_phone_num_with_empty_phone_field" time="3.642"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_010_registration_add_invalid_phone_number" time="3.618"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_010_registration_add_less_than_10_digits_phone_number" time="3.938"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_012_registration_add_more_than_11_digits_phone_number" time="3.632"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_013_registration_add_10_digits_phone_number_successfully" time="3.722"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_014_registration_add_identity_with_empty_user_handle" time="3.504"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_015_Registration_add_empty_identity_alias" time="3.630"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_016_registration_add_empty_identity_value" time="3.720"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_017_registration_add_invalid_identity_alias" time="3.626"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_018_registration_add_lowercase_identity_alias_value" time="3.731"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_019_registration_add_identity_alias_value_as_EIN_to_individual_user" time="3.834"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_020_registration_add_individual_user_identity_with_empty_handle" time="3.514"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_021_registration_add_individual_user_identity_with_another_user_handle" time="3.579"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_022_registration_add_individual_user_identity_with_unregistered_user_handle" time="3.524"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_023_registration_add_individual_user_identity_with_invalid_auth_signature" time="4.409"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_024_registration_add_individual_user_identity_successfull" time="5.442"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_025_registration_add_identity_alias_value_to_already_assigned_user" time="3.702"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_026_registration_add_address_with_empty_address_alias" time="4.241"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_27_registration_add_address_with_empty_street_address_1" time="3.632">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_27_registration_add_address_with_empty_street_address_1(Test_003_Register_add_registration_data.java:525)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_27_registration_add_address_with_empty_street_address_1 -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_028_registration_add_street_address_1_address_with_less_than_3_characters" time="4.401"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_029_registration_add_street_address_1_address_with_3_characters" time="4.235"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_030_registration_add_street_address_1_address_with_40_character" time="4.392"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_031_registration_add_street_address_1_address_with_more_than_max_character" time="4.435"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_032_registration_add_empty_street_address_2_address" time="4.228"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_033_registration_add_street_address_2_address_with_less_than_3_characters" time="4.218"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_034_registration_add_street_address_2_address_with_more_than_max_characters" time="4.378"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_035_registration_add_street_address_2_address_with_40_characters" time="4.202"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_036_registration_add_street_address_2_address_with_3_characters" time="4.166"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_037_registration_add_address_with_empty_city" time="3.796">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_037_registration_add_address_with_empty_city(Test_003_Register_add_registration_data.java:778)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_037_registration_add_address_with_empty_city -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_038_registration_add_address_with_less_than_2_characters_city_name" time="4.466"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_039_registration_add_address_with_more_than_40_characters_city_name" time="4.157"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_040_registration_add_address_with_40_characters_city_name" time="4.340"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_041_registration_add_address_with_empty_state" time="0.689">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_041_registration_add_address_with_empty_state(Test_003_Register_add_registration_data.java:870)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_041_registration_add_address_with_empty_state -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_042_registration_add_adress_with_less_than_2_chars_state_field" time="1.234"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_043_registration_add_adress_with_more_than_2_chars_state_field" time="1.275"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_044_registration_add_address_with_invalid_abbreviations_for_US_states" time="0.636"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_045_registration_add_address_with_empty_postal_code" time="0.637">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_045_registration_add_address_with_empty_postal_code(Test_003_Register_add_registration_data.java:948)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_045_registration_add_address_with_empty_postal_code -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_046_registration_add_address_with_more_than_max_length_postal_code" time="1.273"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_047_registration_add_address_with_10_digitss_postal_code" time="0.652"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_049_registration_add_address_with_empty_country" time="0.619">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_003_Register_add_registration_data.test_049_registration_add_address_with_empty_country(Test_003_Register_add_registration_data.java:1031)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_049_registration_add_address_with_empty_country -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_050_registration_add_address_with_another_country_name" time="1.241"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_051_registration_add_address_with_less_than_2_characters_country_name" time="1.322"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_052_registration_add_address_with_more_than_2_characters_country_name" time="1.265"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_053_registration_add_address_with_lower_case_country_name" time="1.216"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_003_Register_add_registration_data" name="test_054_registration_add_address_successfully" time="1.336"/>
  <system-out/>
</testsuite> <!-- sila_test_cases.Test_003_Register_add_registration_data -->
