<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GOITT5R" failures="7" tests="61" name="sila_test_cases.Test_004_update_registration_data" time="68.461" errors="0" timestamp="2020-12-09T12:54:13 IST" skipped="0">
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_001_registration_update_email_with_empty_user_handle" time="2.767"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_002_registration_update_empty_email_field" time="0.651"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_003_registration_update_invalid_email_field" time="0.642"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_004_registration_update_email_with_invalid_private_key" time="0.637"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_005_registration_update_email_with_not_registered_handle" time="0.635"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_006_registration_update_email_with_more_than_max_email_length" time="0.639">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_006_registration_update_email_with_more_than_max_email_length(Test_004_update_registration_data.java:133)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_006_registration_update_email_with_more_than_max_email_length -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_007_registration_update_email_with_invalid_uuid" time="0.634"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_008_registration_update_email_successfully_with_254_characters_email" time="0.637"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_009_registration_update_phone_num_with_empty_phone_field" time="0.633"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_010_registration_update_invalid_phone_number" time="0.673"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_011_registration_update_phone_number_with_less_than_10_digits" time="0.595"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_012_registration_update_phone_number_with_more_than_10_digits" time="0.640"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_013_registration_update_phone_number_with_invalid_uuid" time="0.638"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_014_registration_update_10_digits_phone_number_successfully" time="0.635"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_015_registration_update_identity_with_empty_identity_alias" time="0.653"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_016_registration_update_identity_with_empty_identity_value" time="0.719"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_017_registration_update_identity_with_invalid_identity_alias" time="1.522"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_018_registration_update_identity_alias_value_in_lowercase" time="1.620"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_019_registration_update_identity_alias_value_as_EIN_to_individual_user" time="1.455"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_020_registration_update_individual_user_identity_successfully" time="1.411"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_021_registration_update_address_with_empty_address_alias" time="1.557">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_021_registration_update_address_with_empty_address_alias(Test_004_update_registration_data.java:429)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_021_registration_update_address_with_empty_address_alias -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_022_registration_update_address_alias" time="1.599"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_023_registration_update_address_with_empty_street_address_1" time="1.592">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_023_registration_update_address_with_empty_street_address_1(Test_004_update_registration_data.java:478)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_023_registration_update_address_with_empty_street_address_1 -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_024_registration_update_street_address_1_address_with_less_than_3_characters" time="1.595"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_025_registration_update_street_address_1_address_with_more_than_max_character" time="1.393"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_026_registration_update_street_address_1_address_with_40_characters" time="1.478"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_027_registration_update_street_address_1_address_with_3_characters" time="1.597"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_028_registration_update_address_with_empty_street_address_2" time="1.599"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_029_registration_update_street_address_2_address_with_less_than_3_characters" time="1.592"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_030_registration_update_street_address_2_address_with_more_than_max_character" time="1.594"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_031_registration_update_street_address_2_address_with_40_characters" time="1.576"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_032_registration_update_street_address_2_address_with_3_characters" time="1.616"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_033_registration_update_address_with_empty_city" time="1.553">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_033_registration_update_address_with_empty_city(Test_004_update_registration_data.java:749)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_033_registration_update_address_with_empty_city -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_034_registration_update_address_with_less_than_2_characters_city_name" time="1.350"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_035_registration_update_address_with_more_than_40_characters_city_name" time="1.567"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_36_registration_update_address_with_40_characters_city_name" time="1.594"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_037_registration_update_address_with_empty_state" time="1.599">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_037_registration_update_address_with_empty_state(Test_004_update_registration_data.java:860)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_037_registration_update_address_with_empty_state -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_038_registration_update_address_with_less_than_2_characters_state_name" time="1.593"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_039_registration_update_address_with_more_than_2_characters_state_name" time="1.589"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_040_registration_update_2_characters_state_name" time="1.358"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_041_registration_update_address_successfully" time="1.538"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_042_registration_update_address_with_another_uuid" time="1.519"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_043_registration_update_address_with_invalid_uuid" time="1.399"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_044_registration_update_with_all_valid_Entity" time="0.901"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_045_registration_update_empty_first_name" time="0.953"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_046_registration_update_first_name_with_min_character" time="0.965"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_047_registration_update_first_name_with_max_character" time="0.950"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_048_registration_update_first_name_with_more_than_40_character" time="0.822"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_049_registration_update_empty_last_name" time="0.769"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_050_registration_update_last_name_with_min_character" time="0.650"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_051_registration_update_last_name_with_max_character" time="0.641"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_052_registration_update_last_name_with_more_than_40_character" time="0.647"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_053_registration_update_empty_entity_name" time="0.926"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_054_registration_update_entity_name_with_min_characters" time="0.941"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_055_registration_update_entity_name_with_max_characters" time="0.649"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_056_registration_update_entity_name_less_than_3_characters" time="0.956">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_056_registration_update_entity_name_less_than_3_characters(Test_004_update_registration_data.java:1299)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_056_registration_update_entity_name_less_than_3_characters -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_057_registration_update_entity_name_more_than_40_characters" time="0.683">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Test_004_update_registration_data.test_057_registration_update_entity_name_more_than_40_characters(Test_004_update_registration_data.java:1314)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_057_registration_update_entity_name_more_than_40_characters -->
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_058_registration_update_birth_date_below_18_years" time="0.905"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_059_registration_update_birth_date_with_future_date" time="0.641"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_060_registration_update_birth_date_as_18_years" time="0.952"/>
  <system-out/>
  <testcase classname="sila_test_cases.Test_004_update_registration_data" name="test_061_registration_update_birth_date_more_than_18_years" time="0.627"/>
  <system-out/>
</testsuite> <!-- sila_test_cases.Test_004_update_registration_data -->
