<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GOITT5R" failures="7" tests="61" name="sila_test_cases.Register_update_registration_data" time="61.306" errors="0" timestamp="2020-11-20T17:23:24 IST" skipped="0">
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_001_registration_update_email_with_empty_user_handle" time="1.153"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_002_registration_update_empty_email_field" time="0.579"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_002_registration_update_invalid_email_field" time="0.635"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_003_registration_update_email_with_invalid_private_key" time="0.636"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_004_registration_update_email_with_not_registered_handle" time="0.461"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_006_registration_update_email_with_more_than_max_email_length" time="0.603">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_006_registration_update_email_with_more_than_max_email_length(Register_update_registration_data.java:133)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_006_registration_update_email_with_more_than_max_email_length -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_007_registration_update_email_with_invalid_uuid" time="0.547"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_008_registration_update_email_successfully_with_254_characters_email" time="0.607"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_009_registration_update_phone_num_with_empty_phone_field" time="0.630"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_010_registration_update_invalid_phone_number" time="0.652"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_011_registration_update_phone_number_with_less_than_10_digits" time="0.630"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_012_registration_update_phone_number_with_more_than_10_digits" time="0.639"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_013_registration_update_phone_number_with_invalid_uuid" time="0.600"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_014_registration_update_10_digits_phone_number_successfully" time="0.662"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_015_registration_update_identity_with_empty_identity_alias" time="0.654"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_016_registration_update_identity_with_empty_identity_value" time="0.615"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_017_registration_update_identity_with_invalid_identity_alias" time="1.593"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_018_registration_update_identity_alias_value_in_lowercase" time="1.411"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_019_registration_update_identity_alias_value_as_EIN_to_individual_user" time="2.158"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_020_registration_update_individual_user_identity_successfully" time="1.347"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_021_registration_update_address_with_empty_address_alias" time="1.260">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_021_registration_update_address_with_empty_address_alias(Register_update_registration_data.java:429)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_021_registration_update_address_with_empty_address_alias -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_022_registration_update_address_alias" time="1.421"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_023_registration_update_address_with_empty_street_address_1" time="1.292">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_023_registration_update_address_with_empty_street_address_1(Register_update_registration_data.java:480)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_023_registration_update_address_with_empty_street_address_1 -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_024_registration_update_street_address_1_address_with_less_than_3_characters" time="1.555"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_025_registration_update_street_address_1_address_with_more_than_max_character" time="1.284"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_026_registration_update_street_address_1_address_with_40_characters" time="1.333"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_027_registration_update_street_address_1_address_with_3_characters" time="1.939"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_028_registration_update_address_with_empty_street_address_2" time="1.301"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_029_registration_update_street_address_2_address_with_less_than_3_characters" time="1.268"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_030_registration_update_street_address_2_address_with_more_than_max_character" time="1.509"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_031_registration_update_street_address_2_address_with_40_characters" time="1.339"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_032_registration_update_street_address_2_address_with_3_characters" time="1.306"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_033_registration_update_address_with_empty_city" time="1.266">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_033_registration_update_address_with_empty_city(Register_update_registration_data.java:755)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_033_registration_update_address_with_empty_city -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_034_registration_update_address_with_less_than_2_characters_city_name" time="1.288"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_035_registration_update_address_with_more_than_40_characters_city_name" time="1.559"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_36_registration_update_address_with_40_characters_city_name" time="1.297"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_037_registration_update_address_with_empty_state" time="1.354">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_037_registration_update_address_with_empty_state(Register_update_registration_data.java:866)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_037_registration_update_address_with_empty_state -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_038_registration_update_address_with_less_than_2_characters_state_name" time="1.432"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_039_registration_update_address_with_more_than_40_characters_state_name" time="1.336"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_040_registration_update_address_with_40_characters_state_name" time="1.291"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_041_registration_update_address_successfully" time="1.363"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_042_registration_update_address_with_another_uuid" time="1.493"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_043_registration_update_address_with_invalid_uuid" time="1.594"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_044_registration_update_empty_first_name" time="0.657"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_045_registration_update_empty_first_name" time="0.934"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_046_registration_update_first_name_with_min_character" time="0.615"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_047_registration_update_first_name_with_max_character" time="0.665"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_048_registration_update_first_name_with_more_than_40_character" time="0.944"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_049_registration_update_empty_last_name" time="0.636"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_050_registration_update_last_name_with_min_character" time="0.634"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_051_registration_update_last_name_with_max_character" time="0.644"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_052_registration_update_last_name_with_more_than_40_character" time="1.017"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_053_registration_update_empty_entity_name" time="0.631"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_054_registration_update_entity_name_with_min_characters" time="0.643"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_055_registration_update_entity_name_with_max_characters" time="0.623"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_056_registration_update_entity_name_less_than_3_characters" time="0.611">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_056_registration_update_entity_name_less_than_3_characters(Register_update_registration_data.java:1305)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_056_registration_update_entity_name_less_than_3_characters -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_057_registration_update_entity_name_more_than_40_characters" time="0.629">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at sila_test_cases.Register_update_registration_data.test_057_registration_update_entity_name_more_than_40_characters(Register_update_registration_data.java:1320)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_057_registration_update_entity_name_more_than_40_characters -->
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_058_registration_update_birth_date_below_18_years" time="0.625"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_059_registration_update_birth_date_with_future_date" time="0.616"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_060_registration_update_birth_date_less_than_18_years" time="0.638"/>
  <system-out/>
  <testcase classname="sila_test_cases.Register_update_registration_data" name="test_061_registration_update_birth_date_more_than_18_years" time="0.652"/>
  <system-out/>
</testsuite> <!-- sila_test_cases.Register_update_registration_data -->
