<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ArcGate2168" failures="0" tests="6" name="sila_test_cases.Check_handle" time="6.292" errors="0" timestamp="2020-11-13T19:35:37 IST" skipped="0">
  <testcase classname="sila_test_cases.Check_handle" name="Test_01_check_with_available_user_handle" time="1.941"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_handle" name="Test_02_check_with_already_taken_user_handle" time="0.473"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_handle" name="Test_03_check_with_empty_user_handle" time="0.727"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_handle" name="Test_04_check_with_invalid_authSignature" time="1.242"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_handle" name="Test_05_check_with_invalid_handle_pattern" time="0.434"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_handle" name="Test_06_check_with_invalid_App_handle" time="1.475"/>
  <system-out/>
</testsuite> <!-- sila_test_cases.Check_handle -->
